//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.3053 版自动生成。
// 
namespace SumPos.SumSerivice {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Service1() {
            this.Url = "http://localhost:8080/SumPosWebService.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCzCardByZh", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getCzCardByZh(string hyzh) {
            object[] results = this.Invoke("getCzCardByZh", new object[] {
                        hyzh});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCzCardByZh(string hyzh, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCzCardByZh", new object[] {
                        hyzh}, callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndgetCzCardByZh(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCzCardByKh", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getCzCardByKh(string hykh) {
            object[] results = this.Invoke("getCzCardByKh", new object[] {
                        hykh});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCzCardByKh(string hykh, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCzCardByKh", new object[] {
                        hykh}, callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndgetCzCardByKh(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCzCardByEnCryStr", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getCzCardByEnCryStr(string enCryStr) {
            object[] results = this.Invoke("getCzCardByEnCryStr", new object[] {
                        enCryStr});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCzCardByEnCryStr(string enCryStr, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCzCardByEnCryStr", new object[] {
                        enCryStr}, callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndgetCzCardByEnCryStr(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/savePay", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool savePay([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] saleFlowListBuff, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] payFlowListBuff) {
            object[] results = this.Invoke("savePay", new object[] {
                        saleFlowListBuff,
                        payFlowListBuff});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsavePay(byte[] saleFlowListBuff, byte[] payFlowListBuff, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("savePay", new object[] {
                        saleFlowListBuff,
                        payFlowListBuff}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndsavePay(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/syncUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] syncUser(string grpno) {
            object[] results = this.Invoke("syncUser", new object[] {
                        grpno});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsyncUser(string grpno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("syncUser", new object[] {
                        grpno}, callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndsyncUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/syncCfg", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] syncCfg(string posno) {
            object[] results = this.Invoke("syncCfg", new object[] {
                        posno});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsyncCfg(string posno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("syncCfg", new object[] {
                        posno}, callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndsyncCfg(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/syncFlow", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool syncFlow([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] saleFlowBuff, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] payFlowBuff) {
            object[] results = this.Invoke("syncFlow", new object[] {
                        saleFlowBuff,
                        payFlowBuff});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsyncFlow(byte[] saleFlowBuff, byte[] payFlowBuff, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("syncFlow", new object[] {
                        saleFlowBuff,
                        payFlowBuff}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndsyncFlow(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/syncSpxinxi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] syncSpxinxi(string grpno) {
            object[] results = this.Invoke("syncSpxinxi", new object[] {
                        grpno});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsyncSpxinxi(string grpno, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("syncSpxinxi", new object[] {
                        grpno}, callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EndsyncSpxinxi(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/userLogon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] userLogon(string usercode, string pwd) {
            object[] results = this.Invoke("userLogon", new object[] {
                        usercode,
                        pwd});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginuserLogon(string usercode, string pwd, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("userLogon", new object[] {
                        usercode,
                        pwd}, callback, asyncState);
        }
        
        /// <remarks/>
        public byte[] EnduserLogon(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChkRight", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ChkRight(string posNo, string sNo) {
            object[] results = this.Invoke("ChkRight", new object[] {
                        posNo,
                        sNo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginChkRight(string posNo, string sNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ChkRight", new object[] {
                        posNo,
                        sNo}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndChkRight(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
    }
}
