//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3053
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.3053 版自动生成。
// 
#pragma warning disable 1591

namespace DebugWebService.WebReference {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SumPosWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class SumPosWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCzCardByZhOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCzCardByKhOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCzCardByEnCryStrOperationCompleted;
        
        private System.Threading.SendOrPostCallback savePayOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback syncFlowOperationCompleted;
        
        private System.Threading.SendOrPostCallback userLogonOperationCompleted;
        
        private System.Threading.SendOrPostCallback czkChzhOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SumPosWebService() {
            this.Url = "http://localhost:8080/SumPosWebService.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event getCzCardByZhCompletedEventHandler getCzCardByZhCompleted;
        
        /// <remarks/>
        public event getCzCardByKhCompletedEventHandler getCzCardByKhCompleted;
        
        /// <remarks/>
        public event getCzCardByEnCryStrCompletedEventHandler getCzCardByEnCryStrCompleted;
        
        /// <remarks/>
        public event savePayCompletedEventHandler savePayCompleted;
        
        /// <remarks/>
        public event syncUserCompletedEventHandler syncUserCompleted;
        
        /// <remarks/>
        public event syncFlowCompletedEventHandler syncFlowCompleted;
        
        /// <remarks/>
        public event userLogonCompletedEventHandler userLogonCompleted;
        
        /// <remarks/>
        public event czkChzhCompletedEventHandler czkChzhCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCzCardByZh", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getCzCardByZh(string hyzh) {
            object[] results = this.Invoke("getCzCardByZh", new object[] {
                        hyzh});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void getCzCardByZhAsync(string hyzh) {
            this.getCzCardByZhAsync(hyzh, null);
        }
        
        /// <remarks/>
        public void getCzCardByZhAsync(string hyzh, object userState) {
            if ((this.getCzCardByZhOperationCompleted == null)) {
                this.getCzCardByZhOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCzCardByZhOperationCompleted);
            }
            this.InvokeAsync("getCzCardByZh", new object[] {
                        hyzh}, this.getCzCardByZhOperationCompleted, userState);
        }
        
        private void OngetCzCardByZhOperationCompleted(object arg) {
            if ((this.getCzCardByZhCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCzCardByZhCompleted(this, new getCzCardByZhCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCzCardByKh", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getCzCardByKh(string hykh) {
            object[] results = this.Invoke("getCzCardByKh", new object[] {
                        hykh});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void getCzCardByKhAsync(string hykh) {
            this.getCzCardByKhAsync(hykh, null);
        }
        
        /// <remarks/>
        public void getCzCardByKhAsync(string hykh, object userState) {
            if ((this.getCzCardByKhOperationCompleted == null)) {
                this.getCzCardByKhOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCzCardByKhOperationCompleted);
            }
            this.InvokeAsync("getCzCardByKh", new object[] {
                        hykh}, this.getCzCardByKhOperationCompleted, userState);
        }
        
        private void OngetCzCardByKhOperationCompleted(object arg) {
            if ((this.getCzCardByKhCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCzCardByKhCompleted(this, new getCzCardByKhCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCzCardByEnCryStr", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getCzCardByEnCryStr(string enCryStr) {
            object[] results = this.Invoke("getCzCardByEnCryStr", new object[] {
                        enCryStr});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void getCzCardByEnCryStrAsync(string enCryStr) {
            this.getCzCardByEnCryStrAsync(enCryStr, null);
        }
        
        /// <remarks/>
        public void getCzCardByEnCryStrAsync(string enCryStr, object userState) {
            if ((this.getCzCardByEnCryStrOperationCompleted == null)) {
                this.getCzCardByEnCryStrOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCzCardByEnCryStrOperationCompleted);
            }
            this.InvokeAsync("getCzCardByEnCryStr", new object[] {
                        enCryStr}, this.getCzCardByEnCryStrOperationCompleted, userState);
        }
        
        private void OngetCzCardByEnCryStrOperationCompleted(object arg) {
            if ((this.getCzCardByEnCryStrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCzCardByEnCryStrCompleted(this, new getCzCardByEnCryStrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/savePay", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string savePay([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] tradeFlowBuff, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] payFlowBuff) {
            object[] results = this.Invoke("savePay", new object[] {
                        tradeFlowBuff,
                        payFlowBuff});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void savePayAsync(byte[] tradeFlowBuff, byte[] payFlowBuff) {
            this.savePayAsync(tradeFlowBuff, payFlowBuff, null);
        }
        
        /// <remarks/>
        public void savePayAsync(byte[] tradeFlowBuff, byte[] payFlowBuff, object userState) {
            if ((this.savePayOperationCompleted == null)) {
                this.savePayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsavePayOperationCompleted);
            }
            this.InvokeAsync("savePay", new object[] {
                        tradeFlowBuff,
                        payFlowBuff}, this.savePayOperationCompleted, userState);
        }
        
        private void OnsavePayOperationCompleted(object arg) {
            if ((this.savePayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.savePayCompleted(this, new savePayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/syncUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] syncUser() {
            object[] results = this.Invoke("syncUser", new object[0]);
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void syncUserAsync() {
            this.syncUserAsync(null);
        }
        
        /// <remarks/>
        public void syncUserAsync(object userState) {
            if ((this.syncUserOperationCompleted == null)) {
                this.syncUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncUserOperationCompleted);
            }
            this.InvokeAsync("syncUser", new object[0], this.syncUserOperationCompleted, userState);
        }
        
        private void OnsyncUserOperationCompleted(object arg) {
            if ((this.syncUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncUserCompleted(this, new syncUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/syncFlow", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool syncFlow([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] tradeFlowBuff, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] payFlowBuff) {
            object[] results = this.Invoke("syncFlow", new object[] {
                        tradeFlowBuff,
                        payFlowBuff});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void syncFlowAsync(byte[] tradeFlowBuff, byte[] payFlowBuff) {
            this.syncFlowAsync(tradeFlowBuff, payFlowBuff, null);
        }
        
        /// <remarks/>
        public void syncFlowAsync(byte[] tradeFlowBuff, byte[] payFlowBuff, object userState) {
            if ((this.syncFlowOperationCompleted == null)) {
                this.syncFlowOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsyncFlowOperationCompleted);
            }
            this.InvokeAsync("syncFlow", new object[] {
                        tradeFlowBuff,
                        payFlowBuff}, this.syncFlowOperationCompleted, userState);
        }
        
        private void OnsyncFlowOperationCompleted(object arg) {
            if ((this.syncFlowCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.syncFlowCompleted(this, new syncFlowCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/userLogon", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] userLogon(string usercode, string pwd) {
            object[] results = this.Invoke("userLogon", new object[] {
                        usercode,
                        pwd});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void userLogonAsync(string usercode, string pwd) {
            this.userLogonAsync(usercode, pwd, null);
        }
        
        /// <remarks/>
        public void userLogonAsync(string usercode, string pwd, object userState) {
            if ((this.userLogonOperationCompleted == null)) {
                this.userLogonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuserLogonOperationCompleted);
            }
            this.InvokeAsync("userLogon", new object[] {
                        usercode,
                        pwd}, this.userLogonOperationCompleted, userState);
        }
        
        private void OnuserLogonOperationCompleted(object arg) {
            if ((this.userLogonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.userLogonCompleted(this, new userLogonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/czkChzh", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] czkChzh([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] chzhFlowBuff) {
            object[] results = this.Invoke("czkChzh", new object[] {
                        chzhFlowBuff});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void czkChzhAsync(byte[] chzhFlowBuff) {
            this.czkChzhAsync(chzhFlowBuff, null);
        }
        
        /// <remarks/>
        public void czkChzhAsync(byte[] chzhFlowBuff, object userState) {
            if ((this.czkChzhOperationCompleted == null)) {
                this.czkChzhOperationCompleted = new System.Threading.SendOrPostCallback(this.OnczkChzhOperationCompleted);
            }
            this.InvokeAsync("czkChzh", new object[] {
                        chzhFlowBuff}, this.czkChzhOperationCompleted, userState);
        }
        
        private void OnczkChzhOperationCompleted(object arg) {
            if ((this.czkChzhCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.czkChzhCompleted(this, new czkChzhCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getCzCardByZhCompletedEventHandler(object sender, getCzCardByZhCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCzCardByZhCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCzCardByZhCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getCzCardByKhCompletedEventHandler(object sender, getCzCardByKhCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCzCardByKhCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCzCardByKhCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void getCzCardByEnCryStrCompletedEventHandler(object sender, getCzCardByEnCryStrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCzCardByEnCryStrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCzCardByEnCryStrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void savePayCompletedEventHandler(object sender, savePayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class savePayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal savePayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void syncUserCompletedEventHandler(object sender, syncUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void syncFlowCompletedEventHandler(object sender, syncFlowCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class syncFlowCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal syncFlowCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void userLogonCompletedEventHandler(object sender, userLogonCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class userLogonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal userLogonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void czkChzhCompletedEventHandler(object sender, czkChzhCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class czkChzhCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal czkChzhCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591